[package]
name = "god_cube2"
version = "0.2.1"
edition = "2021"

[lib]
name = "god_cube2"
path = "src/lib.rs"
# crate-type = ["cdylib", "rlib"]

[[bin]]
name = "GodCube2"
path = "src/main.rs"

[profile.release]
lto = true
